packages:
  - 'apps/*'
  - 'extensions/*'
  - 'packages/*'
  - '!**/templates/**'
allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  leveldown: true
  maplibre-gl: true
  sharp: true
  vue-demi: true
shamefullyHoist: true
