export { default as Table } from './table.vue'
export { default as TableBody } from './table-body.vue'
export { default as TableRow } from './table-row.vue'
export { default as TableCell } from './table-cell.vue'
export { default as TableCaption } from './table-caption.vue'
export { TABLE_DENSITIES } from './variants'
export type { TableColumn, TableColumnAlign, TableDensity } from './types'
