// Anime forms re-exports
export { default as AnimeScoreFormDialog } from './score-form-dialog.vue'
export { AnimeDeleteFormDialog, AnimeBatchDeleteFormDialog } from './delete-form-dialog'
export { default as AnimeMetadataUpdateFormDialog } from './metadata-update-form-dialog/metadata-update-form-dialog.vue'
export { default as AnimeBatchMetadataUpdateFormDialog } from './metadata-update-form-dialog/batch-metadata-update-form-dialog.vue'
export { default as AnimeInfoFormDialog } from './info-form-dialog.vue'
export { default as AnimeNameFormDialog } from './name-form-dialog.vue'
export { default as AnimeOriginalNameFormDialog } from './original-name-form-dialog.vue'
export { default as AnimeDescriptionFormDialog } from './description-form-dialog.vue'
export { default as AnimeStatusFormDialog } from './status-form-dialog.vue'
export { default as AnimeLastActiveFormDialog } from './last-active-form-dialog.vue'
export { default as AnimeFilesConfigFormDialog } from './files-config-form-dialog.vue'
export { AnimeDurationFormDialog } from './duration-form-dialog'
export { AnimeCharactersFormDialog } from './characters-form-dialog'
export { AnimePersonsFormDialog } from './persons-form-dialog'
export { AnimeCompaniesFormDialog } from './companies-form-dialog'
export { AnimeTagsFormDialog } from './tags-form-dialog'
export { AnimeExternalSitesFormDialog } from './external-sites-form-dialog'
export { AnimeExternalIdsFormDialog } from './external-ids-form-dialog'
export { AnimeMediaFormDialog } from './media-form-dialog'
