export { AnimeUpdateHandler } from './anime'
export { CharacterUpdateHandler } from './character'
export { CompanyUpdateHandler } from './company'
export { GameUpdateHandler } from './game'
export { MovieUpdateHandler } from './movie'
export { PersonUpdateHandler } from './person'
export { TvUpdateHandler } from './tv'
