export { AnimeUpdateHandler } from './anime'
export { CharacterUpdateHandler } from './character'
export { ComicUpdateHandler } from './comic'
export { CompanyUpdateHandler } from './company'
export { GameUpdateHandler } from './game'
export { NovelUpdateHandler } from './novel'
export { PersonUpdateHandler } from './person'
