export { applyAnimePlan } from './anime'
export { applyCharacterPlan } from './character'
export { applyCompanyPlan } from './company'
export { applyGamePlan } from './game'
export { applyMoviePlan } from './movie'
export { applyPersonPlan } from './person'
export { applyTvPlan } from './tv'
