packages:
  - 'extensions/*'

allowBuilds:
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@kisaki3/extension-api@__TOOLING_VERSION__'
  - '@kisaki3/extension-cli@__TOOLING_VERSION__'
  - '@kisaki3/extension-registry@__TOOLING_VERSION__'
  - '@kisaki3/extension-sdk@__TOOLING_VERSION__'
  - '@kisaki3/extension-ui-vue@__TOOLING_VERSION__'
