packages:
  - '.'

allowBuilds:
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@kisaki3/extension-api@{{TOOLING_VERSION}}'
  - '@kisaki3/extension-cli@{{TOOLING_VERSION}}'
  - '@kisaki3/extension-registry@{{TOOLING_VERSION}}'
  - '@kisaki3/extension-sdk@{{TOOLING_VERSION}}'
  - '@kisaki3/extension-ui-vue@{{TOOLING_VERSION}}'
